version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_API=http://localhost:5000
    depends_on:
      - server
    restart: always
